# Generated by Django 5.2.1 on 2025-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_numbers', models.CharField(help_text="Separate multiple numbers with '/'", max_length=255)),
                ('whatsapp_viber', models.CharField(help_text="Separate multiple numbers with '/'", max_length=255)),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
                ('linkedin', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/')),
            ],
        ),
    ]
