# Generated by Django 4.2 on 2025-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
