# Generated by Django 5.2.1 on 2025-05-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
