# Generated by Django 5.2.2 on 2025-06-30 05:31

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='Sambeg Khatiwada', max_length=100),
        ),
    ]

